<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NETBIBLE[
<!ELEMENT NETBIBLE (bible+)>
<!ELEMENT bible (title, item+, results)>
<!ELEMENT item (bookname, chapter, verse, text, title?)>
<!ELEMENT bookname (#PCDATA)>
<!ELEMENT chapter (#PCDATA)>
<!ELEMENT verse (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT results (#PCDATA)>
]>
<NETBIBLE>
<bible><title>Genesis 1-50</title><item><bookname>Genesis</bookname><chapter>1</chapter><verse>1</verse><text>In the beginning God created the heavens and the earth.</text><title>The Creation of the World</title></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>2</verse><text>Now the earth was without shape and empty, and darkness was over the surface of the watery deep, but the Spirit of God was moving over the surface of the water.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>3</verse><text>God said, “Let there be light.” And there was light!</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>4</verse><text>God saw that the light was good, so God separated the light from the darkness.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>5</verse><text>God called the light “day” and the darkness “night.” There was evening, and there was morning, marking the first day.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>6</verse><text>God said, “Let there be an expanse in the midst of the waters and let it separate water from water.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>7</verse><text>So God made the expanse and separated the water under the expanse from the water above it. It was so.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>8</verse><text>God called the expanse “sky.” There was evening, and there was morning, a second day.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>9</verse><text>God said, “Let the water under the sky be gathered to one place and let dry ground appear.” It was so.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>10</verse><text>God called the dry ground “land” and the gathered waters he called “seas.” God saw that it was good.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>11</verse><text>God said, “Let the land produce vegetation: plants yielding seeds according to their kinds, and trees bearing fruit with seed in it according to their kinds.” It was so.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>12</verse><text>The land produced vegetation – plants yielding seeds according to their kinds, and trees bearing fruit with seed in it according to their kinds. God saw that it was good.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>13</verse><text>There was evening, and there was morning, a third day.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>14</verse><text>God said, “Let there be lights in the expanse of the sky to separate the day from the night, and let them be signs to indicate seasons and days and years,</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>15</verse><text>and let them serve as lights in the expanse of the sky to give light on the earth.” It was so.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>16</verse><text>God made two great lights – the greater light to rule over the day and the lesser light to rule over the night. He made the stars also.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>17</verse><text>God placed the lights in the expanse of the sky to shine on the earth,</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>18</verse><text>to preside over the day and the night, and to separate the light from the darkness. God saw that it was good.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>19</verse><text>There was evening, and there was morning, a fourth day.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>20</verse><text>God said, “Let the water swarm with swarms of living creatures and let birds fly above the earth across the expanse of the sky.”</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>21</verse><text>God created the great sea creatures and every living and moving thing with which the water swarmed, according to their kinds, and every winged bird according to its kind. God saw that it was good.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>22</verse><text>God blessed them and said, “Be fruitful and multiply and fill the water in the seas, and let the birds multiply on the earth.”</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>23</verse><text>There was evening, and there was morning, a fifth day.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>24</verse><text>God said, “Let the land produce living creatures according to their kinds: cattle, creeping things, and wild animals, each according to its kind.” It was so.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>25</verse><text>God made the wild animals according to their kinds, the cattle according to their kinds, and all the creatures that creep along the ground according to their kinds. God saw that it was good.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>26</verse><text>Then God said, “Let us make humankind in our image, after our likeness, so they may rule over the fish of the sea and the birds of the air, over the cattle, and over all the earth, and over all the creatures that move on the earth.”</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>27</verse><text>God created humankind in his own image, in the image of God he created them, male and female he created them.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>28</verse><text>God blessed them and said to them, “Be fruitful and multiply! Fill the earth and subdue it! Rule over the fish of the sea and the birds of the air and every creature that moves on the ground.”</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>29</verse><text>Then God said, “I now give you every seed-bearing plant on the face of the entire earth and every tree that has fruit with seed in it. They will be yours for food.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>30</verse><text>And to all the animals of the earth, and to every bird of the air, and to all the creatures that move on the ground – everything that has the breath of life in it – I give every green plant for food.” It was so.</text></item><item><bookname>Genesis</bookname><chapter>1</chapter><verse>31</verse><text>God saw all that he had made – and it was very good! There was evening, and there was morning, the sixth day.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>1</verse><text>The heavens and the earth were completed with everything that was in them.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>2</verse><text>By the seventh day God finished the work that he had been doing, and he ceased on the seventh day all the work that he had been doing.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>3</verse><text>God blessed the seventh day and made it holy because on it he ceased all the work that he had been doing in creation.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>4</verse><text>This is the account of the heavens and the earth when they were created – when the Lord God made the earth and heavens.</text><title>The Creation of Man and Woman</title></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>5</verse><text>Now no shrub of the field had yet grown on the earth, and no plant of the field had yet sprouted, for the Lord God had not caused it to rain on the earth, and there was no man to cultivate the ground.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>6</verse><text>Springs would well up from the earth and water the whole surface of the ground.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>7</verse><text>The Lord God formed the man from the soil of the ground and breathed into his nostrils the breath of life, and the man became a living being.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>8</verse><text>The Lord God planted an orchard in the east, in Eden; and there he placed the man he had formed.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>9</verse><text>The Lord God made all kinds of trees grow from the soil, every tree that was pleasing to look at and good for food. (Now the tree of life and the tree of the knowledge of good and evil were in the middle of the orchard.)</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>10</verse><text>Now a river flows from Eden to water the orchard, and from there it divides into four headstreams.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>11</verse><text>The name of the first is Pishon; it runs through the entire land of Havilah, where there is gold.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>12</verse><text>(The gold of that land is pure; pearls and lapis lazuli are also there).</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>13</verse><text>The name of the second river is Gihon; it runs through the entire land of Cush.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>14</verse><text>The name of the third river is Tigris; it runs along the east side of Assyria. The fourth river is the Euphrates.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>15</verse><text>The Lord God took the man and placed him in the orchard in Eden to care for it and to maintain it.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>16</verse><text>Then the Lord God commanded the man, “You may freely eat fruit from every tree of the orchard,</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>17</verse><text>but you must not eat from the tree of the knowledge of good and evil, for when you eat from it you will surely die.”</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>18</verse><text>The Lord God said, “It is not good for the man to be alone. I will make a companion for him who corresponds to him.”</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>19</verse><text>The Lord God formed out of the ground every living animal of the field and every bird of the air. He brought them to the man to see what he would name them, and whatever the man called each living creature, that was its name.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>20</verse><text>So the man named all the animals, the birds of the air, and the living creatures of the field, but for Adam no companion who corresponded to him was found.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>21</verse><text>So the Lord God caused the man to fall into a deep sleep, and while he was asleep, he took part of the man’s side and closed up the place with flesh.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>22</verse><text>Then the Lord God made a woman from the part he had taken out of the man, and he brought her to the man.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>23</verse><text>Then the man said, “This one at last is bone of my bones and flesh of my flesh; this one will be called ‘woman,’ for she was taken out of man.”</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>24</verse><text>That is why a man leaves his father and mother and unites with his wife, and they become a new family.</text></item><item><bookname>Genesis</bookname><chapter>2</chapter><verse>25</verse><text>The man and his wife were both naked, but they were not ashamed.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>1</verse><text>Now the serpent was more shrewd than any of the wild animals that the Lord God had made. He said to the woman, “Is it really true that God said, ‘You must not eat from any tree of the orchard’?”</text><title>The Temptation and the Fall</title></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>2</verse><text>The woman said to the serpent, “We may eat of the fruit from the trees of the orchard;</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>3</verse><text>but concerning the fruit of the tree that is in the middle of the orchard God said, ‘You must not eat from it, and you must not touch it, or else you will die.’”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>4</verse><text>The serpent said to the woman, “Surely you will not die,</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>5</verse><text>for God knows that when you eat from it your eyes will open and you will be like divine beings who know good and evil.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>6</verse><text>When the woman saw that the tree produced fruit that was good for food, was attractive to the eye, and was desirable for making one wise, she took some of its fruit and ate it. She also gave some of it to her husband who was with her, and he ate it.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>7</verse><text>Then the eyes of both of them opened, and they knew they were naked; so they sewed fig leaves together and made coverings for themselves.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>8</verse><text>Then the man and his wife heard the sound of the Lord God moving about in the orchard at the breezy time of the day, and they hid from the Lord God among the trees of the orchard.</text><title>The Judgment Oracles of God at the Fall</title></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>9</verse><text>But the Lord God called to the man and said to him, “Where are you?”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>10</verse><text>The man replied, “I heard you moving about in the orchard, and I was afraid because I was naked, so I hid.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>11</verse><text>And the Lord God said, “Who told you that you were naked? Did you eat from the tree that I commanded you not to eat from?”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>12</verse><text>The man said, “The woman whom you gave me, she gave me some fruit from the tree and I ate it.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>13</verse><text>So the Lord God said to the woman, “What is this you have done?” And the woman replied, “The serpent tricked me, and I ate.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>14</verse><text>The Lord God said to the serpent, “Because you have done this, cursed are you above all the wild beasts and all the living creatures of the field! On your belly you will crawl and dust you will eat all the days of your life.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>15</verse><text>And I will put hostility between you and the woman and between your offspring and her offspring; her offspring will attack your head, and you will attack her offspring’s heel.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>16</verse><text>To the woman he said, “I will greatly increase your labor pains; with pain you will give birth to children. You will want to control your husband, but he will dominate you.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>17</verse><text>But to Adam he said, “Because you obeyed your wife and ate from the tree about which I commanded you, ‘You must not eat from it,’ cursed is the ground thanks to you; in painful toil you will eat of it all the days of your life.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>18</verse><text>It will produce thorns and thistles for you, but you will eat the grain of the field.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>19</verse><text>By the sweat of your brow you will eat food until you return to the ground, for out of it you were taken; for you are dust, and to dust you will return.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>20</verse><text>The man named his wife Eve, because she was the mother of all the living.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>21</verse><text>The Lord God made garments from skin for Adam and his wife, and clothed them.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>22</verse><text>And the Lord God said, “Now that the man has become like one of us, knowing good and evil, he must not be allowed to stretch out his hand and take also from the tree of life and eat, and live forever.”</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>23</verse><text>So the Lord God expelled him from the orchard in Eden to cultivate the ground from which he had been taken.</text></item><item><bookname>Genesis</bookname><chapter>3</chapter><verse>24</verse><text>When he drove the man out, he placed on the eastern side of the orchard in Eden angelic sentries who used the flame of a whirling sword to guard the way to the tree of life.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>1</verse><text>Now the man had marital relations with his wife Eve, and she became pregnant and gave birth to Cain. Then she said, “I have created a man just as the Lord did!”</text><title>The Story of Cain and Abel</title></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>2</verse><text>Then she gave birth to his brother Abel. Abel took care of the flocks, while Cain cultivated the ground.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>3</verse><text>At the designated time Cain brought some of the fruit of the ground for an offering to the Lord.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>4</verse><text>But Abel brought some of the firstborn of his flock – even the fattest of them. And the Lord was pleased with Abel and his offering,</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>5</verse><text>but with Cain and his offering he was not pleased. So Cain became very angry, and his expression was downcast.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>6</verse><text>Then the Lord said to Cain, “Why are you angry, and why is your expression downcast?</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>7</verse><text>Is it not true that if you do what is right, you will be fine? But if you do not do what is right, sin is crouching at the door. It desires to dominate you, but you must subdue it.”</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>8</verse><text>Cain said to his brother Abel, “Let’s go out to the field.” While they were in the field, Cain attacked his brother Abel and killed him.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>9</verse><text>Then the Lord said to Cain, “Where is your brother Abel?” And he replied, “I don’t know! Am I my brother’s guardian?”</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>10</verse><text>But the Lord said, “What have you done? The voice of your brother’s blood is crying out to me from the ground!</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>11</verse><text>So now, you are banished from the ground, which has opened its mouth to receive your brother’s blood from your hand.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>12</verse><text>When you try to cultivate the ground it will no longer yield its best for you. You will be a homeless wanderer on the earth.”</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>13</verse><text>Then Cain said to the Lord, “My punishment is too great to endure!</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>14</verse><text>Look! You are driving me off the land today, and I must hide from your presence. I will be a homeless wanderer on the earth; whoever finds me will kill me.”</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>15</verse><text>But the Lord said to him, “All right then, if anyone kills Cain, Cain will be avenged seven times as much.” Then the Lord put a special mark on Cain so that no one who found him would strike him down.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>16</verse><text>So Cain went out from the presence of the Lord and lived in the land of Nod, east of Eden.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>17</verse><text>Cain had marital relations with his wife, and she became pregnant and gave birth to Enoch. Cain was building a city, and he named the city after his son Enoch.</text><title>The Beginning of Civilization</title></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>18</verse><text>To Enoch was born Irad, and Irad was the father of Mehujael. Mehujael was the father of Methushael, and Methushael was the father of Lamech.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>19</verse><text>Lamech took two wives for himself; the name of the first was Adah, and the name of the second was Zillah.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>20</verse><text>Adah gave birth to Jabal; he was the first of those who live in tents and keep livestock.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>21</verse><text>The name of his brother was Jubal; he was the first of all who play the harp and the flute.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>22</verse><text>Now Zillah also gave birth to Tubal-Cain, who heated metal and shaped all kinds of tools made of bronze and iron. The sister of Tubal-Cain was Naamah.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>23</verse><text>Lamech said to his wives, “Adah and Zillah! Listen to me! You wives of Lamech, hear my words! I have killed a man for wounding me, a young man for hurting me.</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>24</verse><text>If Cain is to be avenged seven times as much, then Lamech seventy-seven times!”</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>25</verse><text>And Adam had marital relations with his wife again, and she gave birth to a son. She named him Seth, saying, “God has given me another child in place of Abel because Cain killed him.”</text></item><item><bookname>Genesis</bookname><chapter>4</chapter><verse>26</verse><text>And a son was also born to Seth, whom he named Enosh. At that time people began to worship the Lord.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>1</verse><text>This is the record of the family line of Adam. When God created humankind, he made them in the likeness of God.</text><title>From Adam to Noah</title></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>2</verse><text>He created them male and female; when they were created, he blessed them and named them “humankind.”</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>3</verse><text>When Adam had lived 130 years he fathered a son in his own likeness, according to his image, and he named him Seth.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>4</verse><text>The length of time Adam lived after he became the father of Seth was 800 years; during this time he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>5</verse><text>The entire lifetime of Adam was 930 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>6</verse><text>When Seth had lived 105 years, he became the father of Enosh.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>7</verse><text>Seth lived 807 years after he became the father of Enosh, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>8</verse><text>The entire lifetime of Seth was 912 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>9</verse><text>When Enosh had lived 90 years, he became the father of Kenan.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>10</verse><text>Enosh lived 815 years after he became the father of Kenan, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>11</verse><text>The entire lifetime of Enosh was 905 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>12</verse><text>When Kenan had lived 70 years, he became the father of Mahalalel.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>13</verse><text>Kenan lived 840 years after he became the father of Mahalalel, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>14</verse><text>The entire lifetime of Kenan was 910 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>15</verse><text>When Mahalalel had lived 65 years, he became the father of Jared.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>16</verse><text>Mahalalel lived 830 years after he became the father of Jared, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>17</verse><text>The entire lifetime of Mahalalel was 895 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>18</verse><text>When Jared had lived 162 years, he became the father of Enoch.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>19</verse><text>Jared lived 800 years after he became the father of Enoch, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>20</verse><text>The entire lifetime of Jared was 962 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>21</verse><text>When Enoch had lived 65 years, he became the father of Methuselah.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>22</verse><text>After he became the father of Methuselah, Enoch walked with God for 300 years, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>23</verse><text>The entire lifetime of Enoch was 365 years.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>24</verse><text>Enoch walked with God, and then he disappeared because God took him away.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>25</verse><text>When Methuselah had lived 187 years, he became the father of Lamech.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>26</verse><text>Methuselah lived 782 years after he became the father of Lamech, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>27</verse><text>The entire lifetime of Methuselah was 969 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>28</verse><text>When Lamech had lived 182 years, he had a son.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>29</verse><text>He named him Noah, saying, “This one will bring us comfort from our labor and from the painful toil of our hands because of the ground that the Lord has cursed.”</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>30</verse><text>Lamech lived 595 years after he became the father of Noah, and he had other sons and daughters.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>31</verse><text>The entire lifetime of Lamech was 777 years, and then he died.</text></item><item><bookname>Genesis</bookname><chapter>5</chapter><verse>32</verse><text>After Noah was 500 years old, he became the father of Shem, Ham, and Japheth.</text></item><item><bookname>Genesis</bookname><chapter>6</chapter><verse>1</verse><text>When humankind began to multiply on the face of the earth, and daughters were born to them,</text><title>God’s Grief over Humankind’s Wickedness</title></item><item><bookname>Genesis</bookname><chapter>6</chapter><verse>2</verse><text>the sons of God saw that the daughters of humankind were beautiful. Thus they took wives for themselves from any they chose.</text></item><item><bookname>Genesis</bookname><chapter>6</chapter><verse>3</verse><text>So the Lord said, “My spirit will not remain in humankind indefinitely, since they are mortal. They will remain for 120 more years.”</text></item><item><bookname>Genesis</bookname><chapter>6</chapter><verse>4</verse><text>The